### ISSUE TITLE
Does this module still supported?

### ISSUE THREAD

**Issue by y-batsianouski** [terraform-aws-modules/terraform-aws-ebs-optimized#11]
# I'm having issues...

## I'm submitting a:

* [ ] bug report
* [ ] feature request
* [x] support request
* [ ] thank you!

Does this module still supported?

**Comment by antonbabenko** [comment]
Not, really. There has been a new data-source added [aws_ec2_instance_type](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ec2_instance_type) which can be used instead of this module.

PR explaining it is welcome. :)

**Comment by y-batsianouski** [comment]
@antonbabenko Thank you to pointing me to that data-source!
Closing.
